[terminal]
vt = 1

[default_session]
command = "tuigreet --issue --time --asterisks --width 72 --theme border=green;text=white;prompt=green;time=cyan;action=green;button=green;container=black;input=white --power-shutdown 'systemctl poweroff' --power-reboot 'systemctl reboot' --cmd /usr/local/bin/forge-xsession"
user = "greeter"
