[terminal]
vt = 1

[general]
source_profile = false

[default_session]
command = "tuigreet --issue --time --remember --remember-session --asterisks --width 72 --greeting 'FORGE owns the workspace' --theme 'border=green;text=white;prompt=green;time=cyan;action=green;button=green;container=black;input=white' --kb-command 2 --kb-sessions 3 --kb-power 5 --power-shutdown 'systemctl poweroff' --power-reboot 'systemctl reboot' --sessions /usr/share/forge-os/wayland-sessions --xsessions /usr/share/forge-os/disabled-xsessions --no-xsession-wrapper --cmd 'startplasma-wayland forge-wayland-session forge-wayland-client'"
user = "greeter"
