#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
record="$root/build/latest.env"
[[ -r "$record" ]] || { echo 'Run scripts/build-forge.sh first.' >&2; exit 1; }
source "$record"
for name in FORGE_SOURCE_COMMIT FORGE_VERSION FORGE_PACKAGE_SHA256 FORGE_LOCK_SHA256 FORGE_RUNTIME_SOURCE_SHA256 FORGE_OS_VERSION FORGE_OS_COMMIT FORGE_OS_OVERLAY_SHA256 FORGE_RUNTIME_RELATIVE_PATH FORGE_EXECUTABLE_RELATIVE_PATH FORGE_EXECUTABLE_SHA256 FORGE_APP_ASAR_SHA256 FORGE_PAYLOAD_SHA256 FORGE_RUNTIME_ID; do
  [[ -n "${!name:-}" ]] || { echo "Missing $name in $record" >&2; exit 1; }
done

overlay_hash() {
  local overlay relative
  while IFS= read -r overlay; do
    relative="${overlay#"$root/"}"
    printf 'FILE %s\n' "$relative"
    sha256sum "$overlay" | awk '{print $1}'
  done < <(find "$root/overlays" -maxdepth 1 -type f -name '*.patch' -print | sort)
}
payload_hash() { (cd "$1"; { find . -type f ! -name .forge-runtime.env -print0 | sort -z | xargs -0 sha256sum; find . -type l -printf 'LINK %p %l\n' | LC_ALL=C sort; }) | sha256sum | awk '{print $1}'; }
record_overlay_executable_permissions() {
  local staged relative mode
  printf '\n# FORGE-OS executable overlay permissions (generated by scripts/build-iso.sh).\n' >>"$profile/profiledef.sh"
  while IFS= read -r -d '' staged; do
    relative="${staged#"$profile/airootfs"}"
    [[ "$relative" == /* && "$relative" != *'"'* && "$relative" != *$'\n'* ]] || { echo "Unsafe executable overlay path: $relative" >&2; exit 1; }
    mode="$(stat -c '%a' "$staged")"
    printf 'file_permissions["%s"]="0:0:%s"\n' "$relative" "$mode" >>"$profile/profiledef.sh"
  done < <(find "$profile/airootfs" -type f -perm /111 -print0 | sort -z)
}
verify_squashfs_executables() {
  local squashfs="$work/iso/arch/x86_64/airootfs.sfs" listing path mode expected
  local -a critical=(
    usr/local/bin/tuigreet
    usr/local/bin/forge-wayland-session
    usr/local/libexec/forge-xdg-environment
    usr/local/libexec/forge-wayland-client
    usr/local/libexec/forge-live-setup
    usr/local/libexec/forge-live-install
    usr/local/libexec/forge-clean-install-core
    usr/local/bin/forge-clean-install
    usr/local/bin/forge-live-guided-install
    usr/local/bin/forge-live-setup-ui
    usr/local/bin/forge-live-select-installer
    usr/local/bin/forge-maintenance-center
    usr/local/bin/forge-service-manager
    usr/local/bin/forge-system-rollback
    usr/local/libexec/forge-service-control
    usr/local/libexec/forge-system-checkpoint
    usr/local/libexec/forge-system-rollback-apply
    usr/local/bin/forge-system-surface
    usr/local/bin/forge-session-control
    usr/local/bin/forge-app-install
    usr/local/bin/forge-install-pkg
    "opt/forge/releases/$FORGE_RUNTIME_ID/$FORGE_EXECUTABLE_RELATIVE_PATH"
    "opt/forge/releases/$FORGE_RUNTIME_ID/chrome-sandbox"
  )
  [[ -r "$squashfs" ]] || { echo "Missing built SquashFS image: $squashfs" >&2; exit 1; }
  command -v unsquashfs >/dev/null || { echo 'Install squashfs-tools to verify the ISO executable modes.' >&2; exit 1; }
  listing="$(unsquashfs -ll "$squashfs" "${critical[@]}")"
  for path in "${critical[@]}"; do
    mode="$(awk -v target="squashfs-root/$path" '$NF == target { print $1 }' <<<"$listing")"
    expected='-rwxr-xr-x'; [[ "$path" == */chrome-sandbox ]] && expected='-rwsr-xr-x'
    [[ "$mode" == "$expected" ]] || { echo "Built ISO executable mode mismatch for /$path: expected $expected, got ${mode:-missing}" >&2; exit 1; }
  done
}

[[ "$FORGE_OS_VERSION" == "$(<"$root/VERSION")" ]] || { echo 'Build record FORGE-OS version mismatch.' >&2; exit 1; }
[[ "$FORGE_OS_OVERLAY_SHA256" == "$(overlay_hash | sha256sum | awk '{print $1}')" ]] || { echo 'Build record overlay hash mismatch.' >&2; exit 1; }
runtime="$root/$FORGE_RUNTIME_RELATIVE_PATH"
runtime_exec="$runtime/$FORGE_EXECUTABLE_RELATIVE_PATH"
work="$root/build/archiso-work"
out="$root/build/iso"
profile="$root/build/archiso-profile"
command -v mkarchiso >/dev/null || { echo 'Install archiso first.' >&2; exit 1; }
[[ -x "$runtime_exec" && -r "$runtime/resources/app.asar" ]] || { echo "Incomplete packaged runtime: $runtime" >&2; exit 1; }
[[ "$(sha256sum "$runtime_exec" | awk '{print $1}')" == "$FORGE_EXECUTABLE_SHA256" ]] || { echo 'Packaged executable hash mismatch.' >&2; exit 1; }
[[ "$(sha256sum "$runtime/resources/app.asar" | awk '{print $1}')" == "$FORGE_APP_ASAR_SHA256" ]] || { echo 'Packaged app.asar hash mismatch.' >&2; exit 1; }
[[ "$(payload_hash "$runtime")" == "$FORGE_PAYLOAD_SHA256" ]] || { echo 'Packaged runtime payload hash mismatch.' >&2; exit 1; }

tuigreet_source="$(readlink -f /usr/local/bin/tuigreet 2>/dev/null || true)"
[[ -x "$tuigreet_source" ]] || { echo 'Run scripts/bootstrap-forgeos.sh first so canonical tuigreet 0.11.0 is installed.' >&2; exit 1; }
[[ -r /usr/share/forge-os/tuigreet-source.env ]] || { echo 'Canonical tuigreet source provenance is missing.' >&2; exit 1; }
grep -Fqx 'repository=https://github.com/tuigreet/tuigreet.git' /usr/share/forge-os/tuigreet-source.env || { echo 'Unexpected tuigreet repository provenance.' >&2; exit 1; }
grep -Fqx 'version=0.11.0' /usr/share/forge-os/tuigreet-source.env || { echo 'Unexpected tuigreet version provenance.' >&2; exit 1; }
grep -Fqx 'commit=6fb15fffb794c6bd357164347d8b6d9e0aa92bbc' /usr/share/forge-os/tuigreet-source.env || { echo 'Unexpected tuigreet commit provenance.' >&2; exit 1; }
/usr/local/bin/tuigreet --version 2>&1 | grep -Fq '0.11.0' || { echo 'ISO source tuigreet is not version 0.11.0.' >&2; exit 1; }
help_text="$("$tuigreet_source" --help 2>&1 || true)"
for option in --background --kb-background --doom-height --matrix-length; do
  grep -Fq -- "$option" <<<"$help_text" || { echo "ISO source tuigreet lacks required option: $option" >&2; exit 1; }
done

[[ "$profile" == "$root/build/archiso-profile" && "$work" == "$root/build/archiso-work" ]] || { echo 'Refusing unexpected archiso build paths.' >&2; exit 1; }
sudo rm -rf -- "$profile" "$work"
cp -a /usr/share/archiso/configs/releng "$profile"

# Keep Arch repositories native and deterministic for the image build. The
# installed OS enables the reviewed community repository during setup.
sed -i '/^#\[multilib\]$/,/^#Include = \/etc\/pacman.d\/mirrorlist$/ { s/^#\[multilib\]$/[multilib]/; s|^#Include = /etc/pacman.d/mirrorlist$|Include = /etc/pacman.d/mirrorlist|; }' "$profile/pacman.conf"
pacman_config_staged="$profile/pacman.conf.staged"
awk -v mirror_file="$root/config/mirrorlist" '
  $0 == "Include = /etc/pacman.d/mirrorlist" {
    found = 0
    while ((getline mirror < mirror_file) > 0) if (mirror ~ /^Server[[:space:]]*=/) { print mirror; found = 1 }
    close(mirror_file); if (!found) exit 42; next
  }
  { print }
' "$profile/pacman.conf" >"$pacman_config_staged" || { echo 'Unable to stage tracked ISO mirrors.' >&2; exit 1; }
mv "$pacman_config_staged" "$profile/pacman.conf"
/usr/bin/pacman-conf --config "$profile/pacman.conf" --repo-list | grep -Fxq multilib || { echo 'ISO does not expose [multilib].' >&2; exit 1; }
for repository in core extra multilib; do
  repository_servers="$(/usr/bin/pacman-conf --config "$profile/pacman.conf" --repo "$repository" Server)"
  grep -q '^https://' <<<"$repository_servers" || { echo "ISO has no tracked HTTPS server for [$repository]." >&2; exit 1; }
done

release="$profile/airootfs/opt/forge/releases/$FORGE_RUNTIME_ID"
install -d \
  "$release" "$profile/airootfs/opt/forge-os" "$profile/airootfs/usr/local/bin" "$profile/airootfs/usr/local/libexec" \
  "$profile/airootfs/etc/xdg/reflector" "$profile/airootfs/usr/share/applications" "$profile/airootfs/usr/share/xdg-desktop-portal" \
  "$profile/airootfs/etc/greetd" "$profile/airootfs/etc/systemd/system/greetd.service.d" "$profile/airootfs/etc/systemd/system/forge-recovery.service.d" \
  "$profile/airootfs/usr/share/forge-os/wayland-sessions" "$profile/airootfs/etc/systemd/system/graphical.target.wants" \
  "$profile/airootfs/etc/systemd/system/getty.target.wants" "$profile/airootfs/etc/systemd/system/multi-user.target.wants" \
  "$profile/airootfs/etc/systemd/system/timers.target.wants" "$profile/airootfs/etc/systemd/user/sockets.target.wants" \
  "$profile/airootfs/etc/systemd/user/default.target.wants"

cp -a "$runtime/." "$release/"
ln -s "releases/$FORGE_RUNTIME_ID" "$profile/airootfs/opt/forge/current"
install -m 4755 "$runtime/chrome-sandbox" "$release/chrome-sandbox"
install -m 0755 "$tuigreet_source" "$profile/airootfs/usr/local/bin/tuigreet"
install -m 0644 /usr/share/forge-os/tuigreet-source.env "$profile/airootfs/usr/share/forge-os/tuigreet-source.env"

install -m 0755 "$root/session/forge-wayland-session" "$profile/airootfs/usr/local/bin/forge-wayland-session"
install -m 0755 "$root/session/forge-xdg-environment" "$profile/airootfs/usr/local/libexec/forge-xdg-environment"
install -m 0755 "$root/session/startplasma-wayland" "$profile/airootfs/usr/local/bin/startplasma-wayland"
install -m 0755 "$root/session/forge-session" "$profile/airootfs/usr/local/bin/forge-session"
install -m 0755 "$root/session/forge-wayland-client" "$profile/airootfs/usr/local/libexec/forge-wayland-client"
install -m 0755 "$root/session/forge-recovery-session" "$profile/airootfs/usr/local/bin/forge-recovery-session"
install -m 0755 "$root/session/forge-recovery-client" "$profile/airootfs/usr/local/libexec/forge-recovery-client"
install -m 0755 "$root/session/forge-plasma-initialize" "$profile/airootfs/usr/local/libexec/forge-plasma-initialize"
install -m 0755 "$root/scripts/forge-runtime-rollback-activate" "$profile/airootfs/usr/local/libexec/forge-runtime-rollback-activate"

for tool in forge-app-launcher forge-open forge-workspace-runner forge-install-program forge-app-install forge-install-pkg forge-panel-manager forge-os-update forge-runtime-rollback forge-workspace-bootstrap forge-refresh-mirrors install-wayland-stacks.sh forge-system-surface forge-session-control forge-service-manager forge-maintenance-center forge-system-rollback; do
  tool_source="$root/scripts/$tool"
  [[ "$tool" == forge-workspace-bootstrap ]] && tool_source="$root/scripts/forge-workspace-bootstrap.sh"
  install -m 0755 "$tool_source" "$profile/airootfs/usr/local/bin/$tool"
done
for helper in forge-service-control forge-system-checkpoint forge-system-rollback-apply; do
  install -m 0755 "$root/scripts/$helper" "$profile/airootfs/usr/local/libexec/$helper"
done

install -m 0755 "$root/scripts/forge-live-setup" "$profile/airootfs/usr/local/libexec/forge-live-setup"
install -m 0755 "$root/scripts/forge-live-install" "$profile/airootfs/usr/local/libexec/forge-live-install"
install -m 0755 "$root/scripts/forge-clean-install" "$profile/airootfs/usr/local/libexec/forge-clean-install-core"
install -m 0755 "$root/scripts/forge-clean-install-wrapper" "$profile/airootfs/usr/local/bin/forge-clean-install"
install -m 0755 "$root/scripts/forge-live-guided-install" "$profile/airootfs/usr/local/bin/forge-live-guided-install"
install -m 0755 "$root/scripts/forge-live-setup-ui" "$profile/airootfs/usr/local/bin/forge-live-setup-ui"
install -m 0755 "$root/scripts/forge-live-select-installer" "$profile/airootfs/usr/local/bin/forge-live-select-installer"

install -m 0644 "$root/config/kwinrc" "$profile/airootfs/etc/xdg/kwinrc"
install -m 0644 "$root/config/kdeglobals" "$profile/airootfs/etc/xdg/kdeglobals"
install -m 0644 "$root/config/reflector.conf" "$profile/airootfs/etc/xdg/reflector/reflector.conf"
install -m 0644 "$root/config/forge-portals.conf" "$profile/airootfs/usr/share/xdg-desktop-portal/forge-portals.conf"
install -m 0644 "$root/manifests/system-services.tsv" "$profile/airootfs/usr/share/forge-os/system-services.tsv"
for desktop in forge-app-launcher.desktop forge-explorer.desktop forge-system-settings.desktop forge-workspace-runner.desktop forge-install-program.desktop forge-panel-manager.desktop forge-live-root-shell.desktop forge-live-installer.desktop forge-live-clean-install.desktop forge-live-setup.desktop; do
  install -m 0644 "$root/session/$desktop" "$profile/airootfs/usr/share/applications/$desktop"
done
for desktop in "$root"/session/forge-internal-*.desktop; do
  install -m 0644 "$desktop" "$profile/airootfs/usr/share/applications/$(basename "$desktop")"
done
install -m 0644 "$root/session/forge.desktop" "$profile/airootfs/usr/share/forge-os/wayland-sessions/forge.desktop"
install -m 0644 "$root/config/greetd-config.toml" "$profile/airootfs/etc/greetd/config.toml"
sed 's/@USER@/forge/g' "$root/config/forge-recovery-greetd.toml" >"$profile/airootfs/etc/greetd/forge-recovery.toml"
install -m 0644 "$root/config/forge-recovery.service" "$profile/airootfs/etc/systemd/system/forge-recovery.service"
install -m 0644 "$root/config/forge-live-setup.service" "$profile/airootfs/etc/systemd/system/forge-live-setup.service"
install -m 0644 "$root/config/forge-dr460nized.fish" "$profile/airootfs/usr/share/forge-os/forge-dr460nized.fish"
install -m 0644 "$root/config/forge-starship.toml" "$profile/airootfs/usr/share/forge-os/forge-starship.toml"
install -m 0644 "$root/config/mirrorlist" "$profile/airootfs/usr/share/forge-os/mirrorlist"
printf '[Unit]\nRequires=forge-live-setup.service\nAfter=forge-live-setup.service\n' >"$profile/airootfs/etc/systemd/system/greetd.service.d/forge-live.conf"
printf '[Unit]\nRequires=forge-live-setup.service\nAfter=forge-live-setup.service\n' >"$profile/airootfs/etc/systemd/system/forge-recovery.service.d/live.conf"
install -m 0644 "$record" "$release/.forge-runtime.env"
install -m 0644 "$root/VERSION" "$profile/airootfs/etc/forge-os-version"
sed -e "s/@VERSION@/$(<"$root/VERSION")/g" -e "s/@SOURCE_COMMIT@/${FORGE_SOURCE_COMMIT:0:12}/g" "$root/config/issue" >"$profile/airootfs/etc/issue"
git -C "$root" archive HEAD | tar -x -C "$profile/airootfs/opt/forge-os"
record_overlay_executable_permissions

sed -i 's/^iso_name=.*/iso_name="forge-os"/' "$profile/profiledef.sh"
sed -i 's/^iso_label=.*/iso_label="FORGE_OS"/' "$profile/profiledef.sh"
while IFS= read -r package; do
  grep -qxF "$package" "$profile/packages.x86_64" || printf '%s\n' "$package" >>"$profile/packages.x86_64"
done < <(sed -e 's/#.*$//' -e '/^[[:space:]]*$/d' "$root/manifests/arch-packages.txt")

ln -sf /usr/lib/systemd/system/greetd.service "$profile/airootfs/etc/systemd/system/graphical.target.wants/greetd.service"
ln -sf /etc/systemd/system/forge-recovery.service "$profile/airootfs/etc/systemd/system/autovt@tty2.service"
ln -sf /usr/lib/systemd/system/greetd.service "$profile/airootfs/etc/systemd/system/display-manager.service"
ln -sf /etc/systemd/system/forge-live-setup.service "$profile/airootfs/etc/systemd/system/multi-user.target.wants/forge-live-setup.service"
for service in NetworkManager.service bluetooth.service firewalld.service irqbalance.service systemd-timesyncd.service cups.service power-profiles-daemon.service ollama.service; do
  ln -sf "/usr/lib/systemd/system/$service" "$profile/airootfs/etc/systemd/system/multi-user.target.wants/$service"
done
for timer in fstrim.timer reflector.timer fwupd-refresh.timer; do
  ln -sf "/usr/lib/systemd/system/$timer" "$profile/airootfs/etc/systemd/system/timers.target.wants/$timer"
done
ln -sf /usr/lib/systemd/user/pipewire.socket "$profile/airootfs/etc/systemd/user/sockets.target.wants/pipewire.socket"
ln -sf /usr/lib/systemd/user/pipewire-pulse.socket "$profile/airootfs/etc/systemd/user/sockets.target.wants/pipewire-pulse.socket"
ln -sf /usr/lib/systemd/user/wireplumber.service "$profile/airootfs/etc/systemd/user/default.target.wants/wireplumber.service"
ln -sf /usr/lib/systemd/system/graphical.target "$profile/airootfs/etc/systemd/system/default.target"

sudo chown root:root "$release/chrome-sandbox"
sudo chmod 4755 "$release/chrome-sandbox"
mkdir -p "$out"
sudo mkarchiso -v -w "$work" -o "$out" "$profile"
verify_squashfs_executables
sha256sum "$out"/*.iso | tee "$out/SHA256SUMS"
echo "Built FORGE-OS ISO $FORGE_OS_VERSION from FORGE $FORGE_SOURCE_COMMIT runtime $FORGE_RUNTIME_ID with canonical tuigreet 0.11.0, Guided Setup, Advanced maintenance, and recovery tools verified in SquashFS."
